package com.yt.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public M setUserName(java.lang.String userName) {
		set("user_name", userName);
		return (M)this;
	}
	
	public java.lang.String getUserName() {
		return getStr("user_name");
	}

	public M setUserAdmin(java.lang.String userAdmin) {
		set("user_admin", userAdmin);
		return (M)this;
	}
	
	public java.lang.String getUserAdmin() {
		return getStr("user_admin");
	}

	public M setUserPass(java.lang.String userPass) {
		set("user_pass", userPass);
		return (M)this;
	}
	
	public java.lang.String getUserPass() {
		return getStr("user_pass");
	}

	public M setUserEmail(java.lang.String userEmail) {
		set("user_email", userEmail);
		return (M)this;
	}
	
	public java.lang.String getUserEmail() {
		return getStr("user_email");
	}

	public M setUserPhoto(java.lang.String userPhoto) {
		set("user_photo", userPhoto);
		return (M)this;
	}
	
	public java.lang.String getUserPhoto() {
		return getStr("user_photo");
	}

	public M setUserRole(java.lang.Integer userRole) {
		set("user_role", userRole);
		return (M)this;
	}
	
	public java.lang.Integer getUserRole() {
		return getInt("user_role");
	}

	public M setUserCreateTime(java.util.Date userCreateTime) {
		set("user_create_time", userCreateTime);
		return (M)this;
	}
	
	public java.util.Date getUserCreateTime() {
		return get("user_create_time");
	}

	public M setUserUpdateTime(java.util.Date userUpdateTime) {
		set("user_update_time", userUpdateTime);
		return (M)this;
	}
	
	public java.util.Date getUserUpdateTime() {
		return get("user_update_time");
	}

}
