package com.yt.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePlaylist<M extends BasePlaylist<M>> extends Model<M> implements IBean {

	public M setPlaylistId(java.lang.Integer playlistId) {
		set("playlist_id", playlistId);
		return (M)this;
	}
	
	public java.lang.Integer getPlaylistId() {
		return getInt("playlist_id");
	}

	public M setPlaylistUser(java.lang.Long playlistUser) {
		set("playlist_user", playlistUser);
		return (M)this;
	}
	
	public java.lang.Long getPlaylistUser() {
		return getLong("playlist_user");
	}

	public M setPlaylistName(java.lang.String playlistName) {
		set("playlist_name", playlistName);
		return (M)this;
	}
	
	public java.lang.String getPlaylistName() {
		return getStr("playlist_name");
	}

	public M setPlaylistPic(java.lang.String playlistPic) {
		set("playlist_pic", playlistPic);
		return (M)this;
	}
	
	public java.lang.String getPlaylistPic() {
		return getStr("playlist_pic");
	}

	public M setPlaylistDate(java.util.Date playlistDate) {
		set("playlist_date", playlistDate);
		return (M)this;
	}
	
	public java.util.Date getPlaylistDate() {
		return get("playlist_date");
	}

}
