package com.yt.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseComment<M extends BaseComment<M>> extends Model<M> implements IBean {

	public M setCommentId(java.lang.Integer commentId) {
		set("comment_id", commentId);
		return (M)this;
	}
	
	public java.lang.Integer getCommentId() {
		return getInt("comment_id");
	}

	public M setCommentPlaylist(java.lang.Long commentPlaylist) {
		set("comment_playlist", commentPlaylist);
		return (M)this;
	}
	
	public java.lang.Long getCommentPlaylist() {
		return getLong("comment_playlist");
	}

	public M setCommentUser(java.lang.Integer commentUser) {
		set("comment_user", commentUser);
		return (M)this;
	}
	
	public java.lang.Integer getCommentUser() {
		return getInt("comment_user");
	}

	public M setCommentContent(java.lang.String commentContent) {
		set("comment_content", commentContent);
		return (M)this;
	}
	
	public java.lang.String getCommentContent() {
		return getStr("comment_content");
	}

	public M setCommentDate(java.util.Date commentDate) {
		set("comment_date", commentDate);
		return (M)this;
	}
	
	public java.util.Date getCommentDate() {
		return get("comment_date");
	}

}
