package com.yt.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMusic<M extends BaseMusic<M>> extends Model<M> implements IBean {

	public M setMusicId(java.lang.Integer musicId) {
		set("music_id", musicId);
		return (M)this;
	}
	
	public java.lang.Integer getMusicId() {
		return getInt("music_id");
	}

	public M setMusicRealid(java.lang.String musicRealid) {
		set("music_realid", musicRealid);
		return (M)this;
	}
	
	public java.lang.String getMusicRealid() {
		return getStr("music_realid");
	}

	public M setMusicTitle(java.lang.String musicTitle) {
		set("music_title", musicTitle);
		return (M)this;
	}
	
	public java.lang.String getMusicTitle() {
		return getStr("music_title");
	}

	public M setMusicAuto(java.lang.String musicAuto) {
		set("music_auto", musicAuto);
		return (M)this;
	}
	
	public java.lang.String getMusicAuto() {
		return getStr("music_auto");
	}

	public M setMusicAuthor(java.lang.String musicAuthor) {
		set("music_author", musicAuthor);
		return (M)this;
	}
	
	public java.lang.String getMusicAuthor() {
		return getStr("music_author");
	}

	public M setMusicCreateDate(java.util.Date musicCreateDate) {
		set("music_create_date", musicCreateDate);
		return (M)this;
	}
	
	public java.util.Date getMusicCreateDate() {
		return get("music_create_date");
	}

}
