package com.yt.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("authorlist", "authorlist_id", Authorlist.class);
		arp.addMapping("comment", "comment_id", Comment.class);
		arp.addMapping("playlist", "playlist_id", Playlist.class);
		arp.addMapping("user", "user_id", User.class);
	}
}

