package com.yt.model;

import com.yt.model.base.BaseAuthorlist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Authorlist extends BaseAuthorlist<Authorlist> {
	public static final Authorlist dao = new Authorlist().dao();
}
