package com.yt.model;

import com.yt.model.base.BasePlaylist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Playlist extends BasePlaylist<Playlist> {
	public static final Playlist dao = new Playlist().dao();
}
